### ISSUE TITLE
ikegamir's impression

### ISSUE THREAD

**Issue by ikegamir-sw** [sw-otay/engorder#1]
@sw-otay 
ひとまずお疲れ様でした！

ありそうなケースを入力してみたところ、いくつかのケースで直感的な動きをしませんでした。
どのような入力がされ、それに対してどのような出力がされることを想定しましたか（＝仕様を整理しましたか）？

自分がこの道具を使うつもりになって考えてみると、よいと思います。

コードについて細かく見るのはその後にします。

**Comment by sw-otay** [comment]
@ikegamir-sw 
レビューありがとうございます！

仕様としては
英文を入力し
（）があれば（）内の単語だけ並び替える
（）がなければ全ての単語を並び替える
と想定していましたが、もう一度確認したところ、）の後の単語の並び替えができていなかったため
修正しました。

**Comment by ikegamir-sw** [comment]
@sw-otay 
プログラムより手前の段階の話が続きますが、これが意識できてるとプロとして結構差が出るのでお付き合いください。

## プログラムより手前の話
ユーザーがやりそうな入力や操作をもう少し想定した方がいいかな、と感じています。
今回のケースで言うと、たとえば……
- 改行が入れられたらどうする
- 2文以上入れられたらどうする
- カンマのある文はどうする
- カッコが全角文字だったらどうする
- etc

大事なのは、これらについて対応することではなく、**こういうケースがあると認識して、そのケースに対して今書いている道具ではどう振る舞うかを決めておくこと**です。
これが仕様を決めるということです。これがガバガバだと現場で手を動かす人が困るわけですね（経験あると思いますが……）。

振る舞いは、費用対効果で決めるといいと思います。
選択肢は、
- 機能として盛り込み、いい感じに動く
- 無視（対応しない）

ちょっと考えてやってみていただければ幸いです。

## プログラムの話
### 名前の話
- 変数名に `sent` って出てきますが、ピンとこず……どんな意味ですか？(別にどこかに送ってないですよね……？)
- `replacedEnglishWord ` の `replace` という単語は「置換する」(=なにかが消えて他のものになる)という意味に感じます。`shuffle` という、振る舞いに対して適切な名前がついた関数がありますから、これを使うのがいいと思います。わたしなら  `shuffledSentence` くらいにするかなぁ。
### 実装の話
- 不必要にリアクティブになってる変数があります。リアクティブは、「画面に出していて」、「値が変わったら画面上でも書き換わる」ためのものでしたよね。
  - もっというと、それらは `replacedEnglishWord` 関数の中でしか使ってなさそうです。ということは、関数の中にスコープを閉じ込めることができそうですよね。

**Comment by sw-otay** [comment]
@ikegamir-sw 
今回の英文並び替えツールとして、ある程度仕様を固めて画面上に記載しました。
お時間のある際にレビューをお願いいたします。

> 変数名に sent って出てきますが、ピンとこず……

Sentenceの意でした。確かに分かりにくいなと思ったので修正しました。

> 不必要にリアクティブになってる変数があります。

変数宣言を見直し、関数の中に入れられるものは入れるようにしました。

**Comment by ikegamir-sw** [comment]
@sw-otay 

# ちっちゃいこと
## コーディングの話
### 1
`var` を使うのはやめましょう
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L30
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L44-L45

### 2
このへんの定義はconstにできますよね(一撃でできるから)
constにできるものはなるべくconstにしてください(不具合の種を減らせるから)
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L11-L12
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L18-L19

このへんも工夫すればできそうですけど、ごちゃごちゃしそうだからこのままでもいい気がする
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L8-L10
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L21-L25

わたしなら正規表現とsplit使うんで `wordNumFront` とかは登場せず、こんなかんじになるかなぁ……
```javascript
let testSentence = ''
let testSentenceKeepFront = ''
let testSentenceKeepBack = ''

if (inputSentence.value.includes('(') && inputSentence.value.includes(')')) {
  [
    testSentenceKeepFront,
    testSentence,
    testSentenceKeepBack,
  ] = inputSentence.value.split(/[\(\)]/)
} else {
  testSentence = inputSentence.value
}
```

### 3
このへんインデントがぐちゃぐちゃですが、気にならないですか？
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L30-L42
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L68-L70

### 4
これってループせずそのまま出せばよくないですか？
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L71-L73

## 仕様の話
### 5
placeholderはユーザーにヒントを与えるための存在です。
変数名を見せられてもわからないと思います。
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L65

### 6
computedで実装されているので、1文字入力されるごとにぴょこぴょこ更新されます。ぜんぜんアリだと思いますが、わたしはこれ鬱陶しく感じちゃうタイプです。
わたしなら「入力」→「なんかボタン押す」→「演算」→「出力」の古き良き形式にします。

## 細かいけど大事なこと
### 似たものの挙動は似せる
これ、testSentenceKeepFront には `(` が含まれず、 testSentenceKeepBack には `)` が含まれますよね。
こういうのは対称にした方が不具合が少なくなると思います。
すなわち、「どっちにもカッコを含める」もしくは「どっちにもカッコを含めない」です。
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L23-L24

ここで `(` 足してるのに
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L34
ここで `)` 足してないのなんでだろうって思っちゃいました。
https://github.com/sw-otay/engorder/blob/9638d3721c442209b8cf29a13487404b3277f73d/src/App.vue#L36
似たものの挙動は似せておくと、コード読んでる人の不安を取り除けます。
ぜひ [リーダブルコード](https://www.amazon.co.jp/dp/4873115655) を読んでください。

**Comment by sw-otay** [comment]
@ikegamir-sw レビューありがとうございます！

正規表現を使用し、かなりスッキリとした形に修正することができました。

>computedで実装されているので、1文字入力されるごとにぴょこぴょこ更新されます。
ボタンを使用するか迷ったのですが、英語の先生が使用される想定だったため
事前に問題用の英文は用意されていてコピペで使用するのではないかと思いボタンは使用しないことにしました。

**Comment by ikegamir-sw** [comment]
@sw-otay こんなもんですかね。
もう一度まっさらから書いてみるといい勉強になるかもしれません。
